apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80        # The port the service listens on internally
      targetPort: 8080 # The port the container is listening on
  type: ClusterIP